client_config_backend: settings
client_config:
  client_id: 867645519759-a2951dqned5pi0a534t592tv48fqnft9.apps.googleusercontent.com
  client_secret: vUrnUdD2YOOkEAMxrSDdrGtF

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

# oauth_scope:
#   - https://www.googleapis.com/auth/drive.file
#   - https://www.googleapis.com/auth/drive.install
#   - https://www.googleapis.com/auth/drive.metadata